### ISSUE TITLE
Vitamin B crashes Rack

### ISSUE THREAD

**Issue by Petervos2018** [xaviershay/vitamin-vcv-modules#1]
Remember this ?

https://community.vcvrack.com/t/vitamin-modules-effect-bypass-and-polyphonic-pan/5636/2?u=yeager

> 26: ZN4rack10appDestroyEv 0x456415
25: ZN12MidiOutWinMM8openPortEjRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x55ae82
24: _C_specific_handler 0x776372fc
23: _chkstk 0x7764bee0
22: RtlInitializeResource 0x7761ff00
21: KiUserExceptionDispatcher 0x7764b5f0
20: CsrVerifyRegion 0x77691e10
19: RtlAllocateHeap 0x77607a30
18: RtlAllocateHeap 0x77607a30
17: malloc 0xfe00137c
16: realloc 0xfe004310
15: ZN4rack3Svg4loadERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE 0x45bd12
14: nvgFill 0x434494
13: ZN4rack3app15ModuleContainer4drawERKNS_6widget6Widget8DrawArgsE 0x577690
12: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
11: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
10: ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE 0x4a7502
9: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
8: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
7: ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE 0x4a30f4
6: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a688c
5: ZN4rack6Window3runEv 0x4594ca
4: main 0x5a41a0
3: main 0x5a41a0
2: main 0x5a41a0
1: BaseThreadInitThunk 0x773d5560
0: RtlUserThreadStart 0x77633840

Greetings Peter.

**Comment by xaviershay** [comment]
ah yes, thanks for making an issue. Sorry haven't been able to track it down yet :(

**Comment by xaviershay** [comment]
Had another go at trying to track this down today:

* Tried running Rack under Valgrind, but Rack would crash before even getting to this module.
* Ran under gdb to get a backtrace on crash (using [this script](https://gist.github.com/ongardie/aa15f1f0d0e6b59890a9)). Identified a number of different crashes, which does suggest memory corruption ... I just still can't figure out where.
* Added assertions at every array access ... this cracked the case! I had an out of bounds write that was corrupting memory.

**Comment by Petervos2018** [comment]
I think this is indeed solved, thank you.
